stages:
- test
- build
- deploy



unit-test:
  stage: test
  image: node:latest
  script: 
  - echo ok


docker-build:
  stage: build
  image: docker:27.3.1
  script: 
  - docker build -t $CI_REGISTRY_IMAGE:latest .
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:latest
  services:
    - docker:dind



deploy-to-k8:
  stage: deploy
  image: 
    name: bitnami/kubectl
    entrypoint: [""]
  script: 
  - cat "$KUBECONFIG_DATA" > .kubeconfig
  - export KUBECONFIG=".kubeconfig"
  - cat .kubeconfig
  - kubectl get pods
  - kubectl apply -f app-2048.yml
