apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
      - name: mon-app
        image: cocadmin/2048-mern
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: jeu-2048
spec:
  type: NodePort
  selector:
    app: jeu-2048
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 5000


